### ISSUE TITLE
Set the default for --run to `npm test`

### ISSUE THREAD

**Issue by BehindTheMath** [papandreou/npm-bisect#4]
The default `test` script for npm can be run by using `npm test`. Perhaps it would make sense to set that as the default for the `--run` option.

**Comment by papandreou** [comment]
That's a good idea. Then we'd need a way to explicitly turn on the interactive mode, though?

**Comment by BehindTheMath** [comment]
Yes.

Truthfully, if you want to follow git's model, the default there is interactive. However, git is used much more broadly and there isn't one default test command, as opposed to Node/npm.

**Comment by papandreou** [comment]
Defaulting to `npm test` could still be surprising in projects that have no test suite, or in cases where the error being tracked down doesn’t manifest itself as the test suite failing.

Since you’ll (hopefully) need a tool like this very rarely I would like to put emphasis on a good interactive experience where the tool guides you towards the right usage. To sort of counteract the power tool-ness a little bit. It would be great if users wouldn’t need to read up on the cli switches at all!

**Comment by BehindTheMath** [comment]
Good point.
