### ISSUE TITLE
Use npm and yarn's Node APIs instead of the CLI

### ISSUE THREAD

**Issue by BehindTheMath** [papandreou/npm-bisect#5]
It looks like the library uses npm and yarn's CLI to install, and then parses the output. Is there a reason not to use their Node APIs?

**Comment by BehindTheMath** [comment]
Actually, TIL that both APIs are undocumented.

**Comment by papandreou** [comment]
It might still be less of a hack to use the programmatic apis, even if they’re undocumented. The current approach of using spawn-wrap and mitm is very hacky.

My long term goal is to demonstrate the value of having a tool like this so that package manager maintainers can be convinced to implement the “install dependencies time machine” feature.

**Comment by BehindTheMath** [comment]
The problem is that the APIs aren't guaranteed to stay the same, since they're not meant to be used externally.
